name: MacOS-Wheels-Build

on:
  push:
    branches: [ "master" ]

jobs:
  build_wheels:
    if: false
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            python: 311
            platform_id: macosx_x86_64
            env:
              MACOSX_DEPLOYMENT_TARGET: 13.0
          - os: macos-14
            python: 311
            platform_id: macosx_x86_64
            env:
              MACOSX_DEPLOYMENT_TARGET: 14.0
          - os: macos-15
            python: 311
            platform_id: macosx_x86_64
            env:
              MACOSX_DEPLOYMENT_TARGET: 15.0

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with: 
          python-version: "3.11" # update once build dependencies are available

      - name: Build Wheels
        run: bash scripts/build_macos_wheels.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: fixed_wheelhouse/*.whl

  publish:
    if: false
    needs: build_wheels
    name: Publish Python 🐍 distribution 📦 to PyPI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            python: 311
            platform_id: macosx_x86_64          
          - os: macos-14
            python: 311
            platform_id: macosx_x86_64
          - os: macos-15
            python: 311
            platform_id: macosx_x86_64

    steps:
      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: dist

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Publish distribution 📦 to PyPI
        env:
          TWINE_REPOSITORY: g-mmpbsa
          TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*

  test_pypi_wheels:
    name: Test PyPI wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            python: 311
            platform_id: macosx_x86_64     
          - os: macos-14
            python: 311
            platform_id: macosx_x86_64
          - os: macos-15
            python: 311
            platform_id: macosx_x86_64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          
      - name: running tests
        run: bash scripts/test_macos_wheels.sh